INSERT INTO generos (nome)
SELECT 'MASCULINO'
    WHERE NOT EXISTS (SELECT 1 FROM generos WHERE nome = 'MASCULINO');

INSERT INTO generos (nome)
SELECT 'FEMININO'
    WHERE NOT EXISTS (SELECT 1 FROM generos WHERE nome = 'FEMININO');

INSERT INTO generos (nome)
SELECT 'OUTRO'
    WHERE NOT EXISTS (SELECT 1 FROM generos WHERE nome = 'OUTRO');

INSERT INTO generos (nome)
SELECT 'NÃO ESPECIFICADO'
    WHERE NOT EXISTS (SELECT 1 FROM generos WHERE nome = 'NÃO ESPECIFICADO');
