name: Deploy do frontend e backend na VM da Azure

on:
  release:
    types: [published]  # Executa o deploy quando lançar uma nova versão

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # ----- Buildar, Transferir e Deploy do Backend -----
      - name: Buildar a imagem do backend
        run: docker build -t backend-image ./backend

      - name: Salvar a imagem do backend
        run: docker save backend-image | gzip > backend-image.tar.gz

      - name: Transferir a imagem do backend para a VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            "
              mkdir -p ~/images/ &&
              cat > ~/images/backend-image.tar.gz
            "

      - name: Parar, remover e rodar o backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            "
              docker stop backend-container || true &&
              docker rm backend-container || true &&
              docker rmi backend-image || true &&
              docker load -i ~/images/backend-image.tar.gz &&
              docker run -d -p 8080:8080 \
                -e SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }} \
                -e SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }} \
                -e SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }} \
                --name backend-container backend-image
            "

      # ----- Buildar, Transferir e Deploy do Frontend -----
      - name: Buildar a imagem do frontend
        run: docker build -t frontend-image ./frontend

      - name: Salvar a imagem do frontend
        run: docker save frontend-image | gzip > frontend-image.tar.gz

      - name: Transferir a imagem do frontend para a VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            "
              mkdir -p ~/images/ &&
              cat > ~/images/frontend-image.tar.gz
            "

      - name: Parar, remover e rodar o frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            "
              docker stop frontend-container || true &&
              docker rm frontend-container || true &&
              docker rmi frontend-image || true &&
              docker load -i ~/images/frontend-image.tar.gz &&
              docker run -d -p 3000:3000 \
                -e VITE_API_URL=${{ secrets.VITE_API_URL }} \
                --name frontend-container frontend-image
            "
